project_name: aws-auth-mapper

builds:
  - id: aam-controller
    main: ./cmd/aam-controller
    binary: aam-controller
    ldflags:
      - -extldflags '-static'
    env:
      - CGO_ENABLED=0
    goos: [ linux ]
    goarch: [ amd64 ]

  - id: aam-terraform-provider
    main: ./cmd/terraform-provider-aws-auth-mapper
    binary: terraform-provider-aws-auth-mapper
    ldflags:
      - -extldflags '-static'
    env:
      - CGO_ENABLED=0
    goos: [ linux ]
    goarch: [ amd64 ]

release:
  prerelease: auto
  name_template: "AWS Auth Mapper {{.Version}}"

  github:
    owner: skpr
    name: aws-auth-mapper

dockers:
  - image_templates:
      - skpr/aws-auth-mapper:latest
      - skpr/aws-auth-mapper:controller-latest
      - skpr/aws-auth-mapper:{{ .Tag }}
      - skpr/aws-auth-mapper:controller-{{ .Tag }}
    dockerfile: dockerfiles/controller/Dockerfile
    build_flag_templates:
      - "--pull"

  - image_templates:
      - skpr/aws-auth-mapper:terraform-latest
      - skpr/aws-auth-mapper:terraform-{{ .Tag }}
    dockerfile: dockerfiles/terraform/Dockerfile
    build_flag_templates:
      - "--pull"