version: 2

builds:
  - id: terraform-provider-aws-auth-mapper
    main: ./cmd/terraform-provider-aws-auth-mapper
    env: [ CGO_ENABLED=0 ]
    goos: [ linux, darwin ]
    goarch: [ amd64, arm64 ]

release:
  prerelease: auto
  github:
    owner: skpr
    name: aws-auth-mapper
