# permissions for end users to edit maproles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: maprole-editor-role
rules:
- apiGroups:
  - iamauthenticator.skpr.io
  resources:
  - maproles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - iamauthenticator.skpr.io
  resources:
  - maproles/status
  verbs:
  - get
