# permissions for end users to view mapusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mapuser-viewer-role
rules:
- apiGroups:
  - iamauthenticator.skpr.io
  resources:
  - mapusers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - iamauthenticator.skpr.io
  resources:
  - mapusers/status
  verbs:
  - get
