/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"time"

	v1beta1 "github.com/skpr/aws-auth-mapper/apis/iamauthenticator/v1beta1"
	scheme "github.com/skpr/aws-auth-mapper/internal/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// MapRolesGetter has a method to return a MapRoleInterface.
// A group's client should implement this interface.
type MapRolesGetter interface {
	MapRoles() MapRoleInterface
}

// MapRoleInterface has methods to work with MapRole resources.
type MapRoleInterface interface {
	Create(*v1beta1.MapRole) (*v1beta1.MapRole, error)
	Update(*v1beta1.MapRole) (*v1beta1.MapRole, error)
	UpdateStatus(*v1beta1.MapRole) (*v1beta1.MapRole, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta1.MapRole, error)
	List(opts v1.ListOptions) (*v1beta1.MapRoleList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.MapRole, err error)
	MapRoleExpansion
}

// mapRoles implements MapRoleInterface
type mapRoles struct {
	client rest.Interface
}

// newMapRoles returns a MapRoles
func newMapRoles(c *IamauthenticatorV1beta1Client) *mapRoles {
	return &mapRoles{
		client: c.RESTClient(),
	}
}

// Get takes name of the mapRole, and returns the corresponding mapRole object, and an error if there is any.
func (c *mapRoles) Get(name string, options v1.GetOptions) (result *v1beta1.MapRole, err error) {
	result = &v1beta1.MapRole{}
	err = c.client.Get().
		Resource("maproles").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of MapRoles that match those selectors.
func (c *mapRoles) List(opts v1.ListOptions) (result *v1beta1.MapRoleList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.MapRoleList{}
	err = c.client.Get().
		Resource("maproles").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested mapRoles.
func (c *mapRoles) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("maproles").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a mapRole and creates it.  Returns the server's representation of the mapRole, and an error, if there is any.
func (c *mapRoles) Create(mapRole *v1beta1.MapRole) (result *v1beta1.MapRole, err error) {
	result = &v1beta1.MapRole{}
	err = c.client.Post().
		Resource("maproles").
		Body(mapRole).
		Do().
		Into(result)
	return
}

// Update takes the representation of a mapRole and updates it. Returns the server's representation of the mapRole, and an error, if there is any.
func (c *mapRoles) Update(mapRole *v1beta1.MapRole) (result *v1beta1.MapRole, err error) {
	result = &v1beta1.MapRole{}
	err = c.client.Put().
		Resource("maproles").
		Name(mapRole.Name).
		Body(mapRole).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *mapRoles) UpdateStatus(mapRole *v1beta1.MapRole) (result *v1beta1.MapRole, err error) {
	result = &v1beta1.MapRole{}
	err = c.client.Put().
		Resource("maproles").
		Name(mapRole.Name).
		SubResource("status").
		Body(mapRole).
		Do().
		Into(result)
	return
}

// Delete takes name of the mapRole and deletes it. Returns an error if one occurs.
func (c *mapRoles) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("maproles").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *mapRoles) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("maproles").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched mapRole.
func (c *mapRoles) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.MapRole, err error) {
	result = &v1beta1.MapRole{}
	err = c.client.Patch(pt).
		Resource("maproles").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
